# 마우스 클릭 및 드래그, 스크롤 활성화
set -g mouse on

# 창(Pane) 이동을 Vim 키바인딩(h, j, k, l)으로 설정 (Ctrl+b 누른 후 h,j,k,l)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 히스토리 버퍼 크기 확장 (기본값보다 길게 스크롤백 가능)
set -g history-limit 10000
